### ISSUE TITLE
IOS8 Compatibility

### ISSUE THREAD

**Issue by hacketo** [inamiy/YIPopupTextView#22]
I had some trouble when using on Ipad2 IOS8 (I dont know if it's the only case), the popupViewHeight results as negative number at the end of the _changePopupViewFrameWithNotification method.
That makes the textView out of the screen and displaying a black screen.
The little hack I did is to reverse the popupViewHeight if the height is negative.

**Comment by bartl-git** [comment]
Same issue

**Comment by inamiy** [comment]
Sorry for being late.
This issue is resolved in #27, so please take a try.
