### ISSUE TITLE
Not working in iOS 10

### ISSUE THREAD

**Issue by rahulvyas** [inamiy/YIPopupTextView#34]
When we present it in iOS 10 on iPhone 5S it hides behind the navigation bar.
It's working fine in iOS 9.x though in iPhone 5S

**Comment by inamiy** [comment]
I tested it with the bundled demo app, but I don't see any issues.
Can you reproduce the bug from demo app?

**Comment by rahulvyas** [comment]
I have view heirarchy like this. View Controller A NavigationBar is hidden and when I show Popup TextView it get on top of status bar. View Controller B navigation bar not hidden and when I show the Popup Text view it shows behind the navigation bar. The same thing is working in iOS 9.X

**Comment by inamiy** [comment]
I can't figure out what is the relationship between ViewController A and B.
As I just said earlier, can you reproduce the bug from demo app?

By the way, if you are controlling (hiding/showing) navigationBar quite often, there may be a timing-dependent bug which I think it can be fixed on your side, by slightly delaying the popup or navigationBar.

**Comment by rahulvyas** [comment]
The issue is fixed you can close the bug.
I replaced the files from your files.
By the way I guess you should support cocoa pods.

**Comment by inamiy** [comment]
Awesome! OK, I will bump it soon.
